/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facturacion;

import com.mysql.jdbc.Connection;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author villegasevil
 */
public class RegistroProductos extends javax.swing.JFrame {

    DefaultTableModel modeloPro;
    
    public RegistroProductos() {
        initComponents();
        mostrarRegistros();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t_idPro = new javax.swing.JTextField();
        t_nomPro = new javax.swing.JTextField();
        t_marcaProd = new javax.swing.JTextField();
        t_precioPro = new javax.swing.JTextField();
        BotonRegiProd = new javax.swing.JButton();
        BotonAtrasProd = new javax.swing.JButton();
        BotonSalir2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPro = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        t_buscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("INGRESO DE DATOS DEL PRODUCTO");

        jLabel2.setText("Id:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Marca:");

        jLabel5.setText("Precio:");

        t_idPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_idProActionPerformed(evt);
            }
        });

        t_marcaProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_marcaProdActionPerformed(evt);
            }
        });

        t_precioPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_precioProActionPerformed(evt);
            }
        });

        BotonRegiProd.setText("Registrar");
        BotonRegiProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegiProdActionPerformed(evt);
            }
        });

        BotonAtrasProd.setText("Atras");
        BotonAtrasProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAtrasProdActionPerformed(evt);
            }
        });

        BotonSalir2.setText("Salir");
        BotonSalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalir2ActionPerformed(evt);
            }
        });

        tablaPro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaPro);

        jLabel6.setText("Registro de Productos:");

        jLabel7.setText("Buscar por Codigo:");

        t_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_buscarActionPerformed(evt);
            }
        });
        t_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t_buscarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotonAtrasProd)
                            .addComponent(BotonSalir2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(t_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t_idPro)
                            .addComponent(t_marcaProd)
                            .addComponent(t_nomPro, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(t_precioPro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(BotonRegiProd)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(t_idPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(t_nomPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(t_marcaProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(t_precioPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BotonRegiProd)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(t_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(BotonAtrasProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotonSalir2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t_idProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_idProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_idProActionPerformed

    private void t_marcaProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_marcaProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_marcaProdActionPerformed

    private void t_precioProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_precioProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_precioProActionPerformed

    private void BotonRegiProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegiProdActionPerformed
        registrarProductos();
    }//GEN-LAST:event_BotonRegiProdActionPerformed

    private void BotonAtrasProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAtrasProdActionPerformed
        this.setVisible(false);
        Sistema sist= new Sistema();
        sist.setVisible(true);
    }//GEN-LAST:event_BotonAtrasProdActionPerformed

    private void BotonSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalir2ActionPerformed
        dispose();
    }//GEN-LAST:event_BotonSalir2ActionPerformed

    private void t_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_buscarActionPerformed

    private void t_buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_buscarKeyReleased
        buscar(t_buscar.getText());
    }//GEN-LAST:event_t_buscarKeyReleased

     private void buscar(String valor){
       
        try{
          
        String []titulos={"Codigo","Nombre","Marca","Precio"};
        String []fila=new String [4];    
        
        String sql= "select *from productos  where nom_Prod LIKE '%"+valor+"%'";
        modeloPro= new DefaultTableModel(null,titulos);
        BaseDatos connect= new BaseDatos();
        Connection cnn= (Connection) connect.conexion();
        
        Statement st = cnn.createStatement();
        ResultSet rs= st.executeQuery(sql);
        
        while(rs.next()){
                fila[0]= rs.getString("id_Prod");
                fila[1]= rs.getString("nom_Prod");
                fila[2]= rs.getString("marca_Prod");
                fila[3]= rs.getString("precio_Prod");
                modeloPro.addRow(fila);       
        }  
        tablaPro.setModel(modeloPro);
        }catch(SQLException  e){
            JOptionPane.showMessageDialog(null,e);
        }     
    }
    
    
    private void mostrarRegistros(){
       
        try{
          
        String []titulos={"Codigo","Nombre","Marca","Precio"};
        String []fila=new String [4];    
        
        String sql= "select *from productos";
        modeloPro= new DefaultTableModel(null,titulos);
        BaseDatos connect= new BaseDatos();
        Connection cnn= (Connection) connect.conexion();
        
        Statement st = cnn.createStatement();
        ResultSet rs= st.executeQuery(sql);
        
        while(rs.next()){
                fila[0]= rs.getString("id_Prod");
                fila[1]= rs.getString("nom_Prod");
                fila[2]= rs.getString("marca_Prod");
                fila[3]= rs.getString("precio_Prod");
                modeloPro.addRow(fila);       
        }  
        tablaPro.setModel(modeloPro);
        }catch(SQLException  e){
            JOptionPane.showMessageDialog(null,e);
        }   
    }
    private void registrarProductos(){
        String nombre= t_nomPro.getText();
        String id=t_idPro.getText();
        String marca= t_marcaProd.getText();
        String  precio= t_precioPro.getText();

        if(nombre.equals("")|| id.equals("")|| marca.equals("")||precio.equals("")){
            JOptionPane.showMessageDialog(this,"Ingrese los datos");           
        }else{
            Double prec= Double.parseDouble(t_precioPro.getText());
            if(prec==0) {
                JOptionPane.showMessageDialog(this,"Ingrese un valor para el producto");
            }else{
                
                    //JOptionPane.showMessageDialog(this,"Registro Exitoso");
                    BaseDatos connect= new BaseDatos();
                    Connection cn= (Connection) connect.conexion();
                    String sql="";
                    sql="INSERT INTO productos (id_Prod, nom_Prod, marca_Prod, precio_Prod) VALUES(?,?,?,?)";
                 try {
                    PreparedStatement psd= cn.prepareStatement(sql);
                    psd.setString(1, id);
                    psd.setString(2, nombre);
                    psd.setString(3, marca);
                    psd.setString(4, precio);
                    int n= psd.executeUpdate();
                    
                    if(n>0){
                        JOptionPane.showMessageDialog(null,"Registro Exitoso" );                       
                        t_nomPro.setText("");
                        t_idPro.setText("");
                        t_marcaProd.setText("");
                        t_precioPro.setText("");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(RegistroProductos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAtrasProd;
    private javax.swing.JButton BotonRegiProd;
    private javax.swing.JButton BotonSalir2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t_buscar;
    private javax.swing.JTextField t_idPro;
    private javax.swing.JTextField t_marcaProd;
    private javax.swing.JTextField t_nomPro;
    private javax.swing.JTextField t_precioPro;
    private javax.swing.JTable tablaPro;
    // End of variables declaration//GEN-END:variables
}
